### ISSUE TITLE
ERROR RuntimeError: Wrong type NilClass. Not allowed!

### ISSUE THREAD

**Issue by peisert** [elliotekj/orbit#3]
I've been trying all kinds of things to get Orbit working on Sonoma 14.1.2 including both running with older Ruby / libraries as well as running modern Ruby (3.2.2) and modern libraries.  So far nothing has worked.  In the case of the latter, I'm getting the errors below.  I wonder if you have any thoughts on how to fix this?

[2023-12-10 11:46:26] INFO  WEBrick 1.8.1
[2023-12-10 11:46:26] INFO  ruby 3.2.2 (2023-03-30) [arm64-darwin23]
[2023-12-10 11:46:26] INFO  WEBrick::HTTPServer#start: pid=25919 port=4040
[2023-12-10 11:46:28] ERROR RuntimeError: Wrong type NilClass. Not allowed!
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:205:in `conv2value'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:227:in `block in conv2value'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:224:in `each'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:224:in `collect'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:224:in `conv2value'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:234:in `block in conv2value'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:234:in `collect'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:234:in `conv2value'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:227:in `block in conv2value'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:224:in `each'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:224:in `collect'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:224:in `conv2value'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:234:in `block in conv2value'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:234:in `collect'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:234:in `conv2value'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:151:in `block in methodResponse'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:150:in `collect'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/create.rb:150:in `methodResponse'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/server.rb:346:in `handle'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/server.rb:286:in `process'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/xmlrpc-0.3.3/lib/xmlrpc/server.rb:693:in `service'
	/Users/sean/Scripts/orbit-master/app/orbit/servlet.rb:17:in `service'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:140:in `service'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:96:in `run'
	/opt/homebrew/lib/ruby/gems/3.2.0/gems/webrick-1.8.1/lib/webrick/server.rb:310:in `block in start_thread'
::1 - - [10/Dec/2023:11:46:28 PST] "POST /xmlrpc HTTP/1.1" 500 313
- -> /xmlrpc
^C[2023-12-10 11:46:48] INFO  going to shutdown ...
[2023-12-10 11:46:48] INFO  WEBrick::HTTPServer#start done.

**Comment by peisert** [comment]
Line #17 in servlet.rb is just `super`
